#compdef afl-cmin.bash

# Autogenerated from man page
# Updated with latest AFL++ afl-cmin.bash options

local arguments

arguments=(
    '-i[Input directory with the starting corpus]:directory:_directories'
    '-o[Output directory for minimized files]:directory:_directories'
    '-f[Location read by the fuzzed program (default: stdin)]:file:_files'
    '-m[Memory limit for child process in MB (default: 200)]:megabytes'
    '-t[Run time limit for child process in ms (default: none)]:milliseconds'
    '-Q[Use binary-only instrumentation (QEMU mode)]'
    '-U[Use unicorn-based instrumentation (Unicorn mode)]'
    '-C[Keep crashing inputs, reject everything else]'
    '-e[Solve for edge coverage only, ignore hit counts]'
    '*:target command:_files'
)
_arguments -s $arguments
