#compdef alsa-info alsa-info.sh

# Autogenerated from man page /usr/share/man/man1/alsa-info.sh.1.gz
# Updated with latest alsa-info options

local arguments

arguments=(
    '--upload[Upload contents to the server (www.alsa-project.org)]'
    '--no-upload[Do not upload contents to the remote server]'
    '--stdout[Print information to standard output]'
    '--output[Specify file for output in no-upload mode]:FILE:_files'
    '--debug[Run utility as normal, but will not delete temp file]'
    '--with-aplay[Include output from aplay -l]'
    '--with-amixer[Include output from amixer]'
    '--with-alsactl[Include output from alsactl]'
    '--with-configs[Include output from ~/.asoundrc and /etc/asound.conf if they exist]'
    '--update[Check server for updates]'
    '--about[Print information about authors]'
    '*:filename:_files'
)
_arguments -s $arguments
