#compdef scandeps.pl

# Autogenerated from man page /usr/share/man/man1/scandeps.pl.1
# Updated with fixes for troff artifacts and wrong compdef

local arguments

arguments=(
    {-e,--eval}'[Scan STRING as a string containing perl code]:string'
    {-c,--compile}'[Compile the code and inspect %INC, in addition to static scanning]'
    {-x,--execute}'[Execute the code and inspect %INC, in addition to static scanning]'
    '--xargs[If -x is given, split the STRING using the function and pass as @ARGV]:string'
    {-B,--bundle}'[Include core modules in the output and the recursive search list]'
    {-R,--no-recurse}'[Only show dependencies found in the files listed, do not recurse]'
    {-V,--verbose}'[Verbose mode: Output all files found during the process]'
    {-C,--cachedeps}'[Use CACHEFILE to speed up the scanning process by caching dependencies]:cachefile:_files'
    '*:filename:_files'
)
_arguments -s $arguments
