#compdef scandeps

# Autogenerated from man page /usr/share/man/man1/scandeps.pl.1

local arguments

arguments=(
    '-e[Scan \\s-1STRING\\s0 as a string containing perl code.]:s-1STRINGs0'
    '-c[Compiles the code and inspects its \\f(CW%INC, in addition to static scanning.]'
    '-x[Executes the code and inspects its \\f(CW%INC, in addition to static scanning.]'
    '-B[Include core modules in the output and the recursive search list.]'
    '-R[Only show dependencies found in the files listed and do not recurse.]'
    '-V[Verbose mode: Output all files found during the process; show dependencies b…]'
    '*:filename:_files'
)
_arguments -s $arguments
