#!/usr/bin/env zunit
#{{{                    MARK:Header
#**************************************************************
##### Author: MenkeTechnologies
##### GitHub: https://github.com/MenkeTechnologies
##### Purpose: Content tests for man_src/ completion files
#}}}***********************************************************

@setup {
    unset -m "ZPWR_*"
    0="${${0:#$ZSH_ARGZERO}:-${(%):-%N}}"
    0="${${(M)0:#/*}:-$PWD/$0}"
    pluginDir="${0:h:A}"
    msrc="$pluginDir/man_src"
}

# ─── file existence ───────────────────────────────────────────────────────────

@test 'man_src has _nginx' {
    assert "$msrc/_nginx" is_file
}

@test 'man_src has _python' {
    assert "$msrc/_python" is_file
}

@test 'man_src has _head' {
    assert "$msrc/_head" is_file
}

@test 'man_src has _a2x' {
    assert "$msrc/_a2x" is_file
}

@test 'man_src has _zeek' {
    assert "$msrc/_zeek" is_file
}

@test 'man_src has _abrt' {
    assert "$msrc/_abrt" is_file
}

@test 'man_src has _zic' {
    assert "$msrc/_zic" is_file
}

# ─── Autogenerated comment ────────────────────────────────────────────────────

@test 'man_src/_nginx has Autogenerated comment' {
    run grep -c 'Autogenerated' "$msrc/_nginx"
    assert $state equals 0
}

@test 'man_src/_python has Autogenerated comment' {
    run grep -c 'Autogenerated' "$msrc/_python"
    assert $state equals 0
}

@test 'man_src/_head has Autogenerated comment' {
    run grep -c 'Autogenerated' "$msrc/_head"
    assert $state equals 0
}

@test 'man_src/_a2x has Autogenerated comment' {
    run grep -c 'Autogenerated' "$msrc/_a2x"
    assert $state equals 0
}

@test 'man_src/_zeek has Autogenerated comment' {
    run grep -c 'Autogenerated' "$msrc/_zeek"
    assert $state equals 0
}

# ─── _nginx content ───────────────────────────────────────────────────────────

@test 'man_src/_nginx compdef is nginx' {
    run head -1 "$msrc/_nginx"
    assert $output same_as '#compdef nginx'
}

@test 'man_src/_nginx has -c config flag' {
    run grep -cF -- '-c[' "$msrc/_nginx"
    assert $state equals 0
}

@test 'man_src/_nginx has -t test flag' {
    run grep -cF -- '-t[' "$msrc/_nginx"
    assert $state equals 0
}

@test 'man_src/_nginx has -V version flag' {
    run grep -cF -- '-V[' "$msrc/_nginx"
    assert $state equals 0
}

@test 'man_src/_nginx has -v version flag' {
    run grep -cF -- '-v[' "$msrc/_nginx"
    assert $state equals 0
}

@test 'man_src/_nginx has -s signal flag' {
    run grep -cF -- '-s[' "$msrc/_nginx"
    assert $state equals 0
}

@test 'man_src/_nginx has -p prefix flag' {
    run grep -cF -- '-p[' "$msrc/_nginx"
    assert $state equals 0
}

@test 'man_src/_nginx has -q quiet flag' {
    run grep -cF -- '-q[' "$msrc/_nginx"
    assert $state equals 0
}

@test 'man_src/_nginx uses _arguments' {
    run grep -c '_arguments' "$msrc/_nginx"
    assert $state equals 0
}

@test 'man_src/_nginx completes filenames' {
    run grep -c '_files' "$msrc/_nginx"
    assert $state equals 0
}

@test 'man_src/_nginx passes syntax check' {
    run zsh -n "$msrc/_nginx"
    assert $state equals 0
}

# ─── _python content ──────────────────────────────────────────────────────────

@test 'man_src/_python compdef is python2' {
    run head -1 "$msrc/_python"
    assert $output same_as '#compdef python2 python'
}

@test 'man_src/_python has -c command flag' {
    run grep -cF -- '-c[' "$msrc/_python"
    assert $state equals 0
}

@test 'man_src/_python has -v verbose flag' {
    run grep -cF -- '-v[' "$msrc/_python"
    assert $state equals 0
}

@test 'man_src/_python has -m module flag' {
    run grep -cF -- '-m[' "$msrc/_python"
    assert $state equals 0
}

@test 'man_src/_python has -i interactive flag' {
    run grep -cF -- '-i[' "$msrc/_python"
    assert $state equals 0
}

@test 'man_src/_python has --version flag' {
    run grep -cF -- '--version' "$msrc/_python"
    assert $state equals 0
}

@test 'man_src/_python has --help flag' {
    run grep -c 'help' "$msrc/_python"
    assert $state equals 0
}

@test 'man_src/_python uses _arguments' {
    run grep -c '_arguments' "$msrc/_python"
    assert $state equals 0
}

@test 'man_src/_python passes syntax check' {
    run zsh -n "$msrc/_python"
    assert $state equals 0
}

# ─── _head content ────────────────────────────────────────────────────────────

@test 'man_src/_head compdef is head' {
    run head -1 "$msrc/_head"
    assert $output same_as '#compdef head'
}

@test 'man_src/_head has --bytes flag' {
    run grep -c 'bytes' "$msrc/_head"
    assert $state equals 0
}

@test 'man_src/_head has --lines flag' {
    run grep -c 'lines' "$msrc/_head"
    assert $state equals 0
}

@test 'man_src/_head has --quiet flag' {
    run grep -c 'quiet' "$msrc/_head"
    assert $state equals 0
}

@test 'man_src/_head has --verbose flag' {
    run grep -c 'verbose' "$msrc/_head"
    assert $state equals 0
}

@test 'man_src/_head has --help flag' {
    run grep -c 'help' "$msrc/_head"
    assert $state equals 0
}

@test 'man_src/_head has --version flag' {
    run grep -c 'version' "$msrc/_head"
    assert $state equals 0
}

@test 'man_src/_head completes filenames' {
    run grep -c '_files' "$msrc/_head"
    assert $state equals 0
}

@test 'man_src/_head uses _arguments' {
    run grep -c '_arguments' "$msrc/_head"
    assert $state equals 0
}

@test 'man_src/_head passes syntax check' {
    run zsh -n "$msrc/_head"
    assert $state equals 0
}

# ─── _a2x content ─────────────────────────────────────────────────────────────

@test 'man_src/_a2x compdef is a2x' {
    run head -1 "$msrc/_a2x"
    assert $output same_as '#compdef a2x'
}

@test 'man_src/_a2x has --format flag' {
    run grep -c 'format' "$msrc/_a2x"
    assert $state equals 0
}

@test 'man_src/_a2x has --verbose flag' {
    run grep -c 'verbose' "$msrc/_a2x"
    assert $state equals 0
}

@test 'man_src/_a2x has --dry-run flag' {
    run grep -c 'dry-run' "$msrc/_a2x"
    assert $state equals 0
}

@test 'man_src/_a2x has --help flag' {
    run grep -c 'help' "$msrc/_a2x"
    assert $state equals 0
}

@test 'man_src/_a2x has --version flag' {
    run grep -c 'version' "$msrc/_a2x"
    assert $state equals 0
}

@test 'man_src/_a2x uses _arguments' {
    run grep -c '_arguments' "$msrc/_a2x"
    assert $state equals 0
}

@test 'man_src/_a2x passes syntax check' {
    run zsh -n "$msrc/_a2x"
    assert $state equals 0
}

# ─── _zeek content ────────────────────────────────────────────────────────────

@test 'man_src/_zeek compdef is zeek' {
    run head -1 "$msrc/_zeek"
    assert $output same_as '#compdef zeek'
}

@test 'man_src/_zeek has --parse-only flag' {
    run grep -c 'parse-only' "$msrc/_zeek"
    assert $state equals 0
}

@test 'man_src/_zeek has --bare-mode flag' {
    run grep -c 'bare-mode' "$msrc/_zeek"
    assert $state equals 0
}

@test 'man_src/_zeek has --iface flag' {
    run grep -c 'iface' "$msrc/_zeek"
    assert $state equals 0
}

@test 'man_src/_zeek has --version flag' {
    run grep -c 'version' "$msrc/_zeek"
    assert $state equals 0
}

@test 'man_src/_zeek has --filter flag' {
    run grep -c 'filter' "$msrc/_zeek"
    assert $state equals 0
}

@test 'man_src/_zeek uses _arguments' {
    run grep -c '_arguments' "$msrc/_zeek"
    assert $state equals 0
}

@test 'man_src/_zeek passes syntax check' {
    run zsh -n "$msrc/_zeek"
    assert $state equals 0
}

# ─── _abrt content ────────────────────────────────────────────────────────────

@test 'man_src/_abrt compdef is abrt' {
    run head -1 "$msrc/_abrt"
    assert $output same_as '#compdef abrt'
}

@test 'man_src/_abrt has --help flag' {
    run grep -c 'help' "$msrc/_abrt"
    assert $state equals 0
}

@test 'man_src/_abrt has --version flag' {
    run grep -c 'version' "$msrc/_abrt"
    assert $state equals 0
}

@test 'man_src/_abrt uses _arguments' {
    run grep -c '_arguments' "$msrc/_abrt"
    assert $state equals 0
}

@test 'man_src/_abrt passes syntax check' {
    run zsh -n "$msrc/_abrt"
    assert $state equals 0
}

# ─── man_src overall quality ──────────────────────────────────────────────────

@test 'majority of man_src files reference a man page path' {
    local count_auto count_total
    count_auto=$(grep -rl 'Autogenerated from man page' "$msrc/" | wc -l | tr -d ' ')
    count_total=$(ls "$msrc/" | wc -l | tr -d ' ')
    local pct=$(( count_auto * 100 / count_total ))
    assert $pct is_greater_than 50
}

@test 'man_src files all use _arguments' {
    local bad=0
    for f in "$msrc/"_*; do
        grep -qF '_arguments' "$f" || (( bad += 1 )) || true
    done
    assert $bad equals 0
}

@test 'vast majority of man_src files end with _arguments -s call' {
    local match=0 total=0
    for f in "$msrc/"_*; do
        (( total += 1 ))
        grep -qF '_arguments -s $arguments' "$f" && (( match += 1 )) || true
    done
    local pct=$(( match * 100 / total ))
    assert $pct is_greater_than 95
}

@test 'vast majority of man_src files declare local arguments' {
    local match=0 total=0
    for f in "$msrc/"_*; do
        (( total += 1 ))
        grep -qF 'local arguments' "$f" && (( match += 1 )) || true
    done
    local pct=$(( match * 100 / total ))
    assert $pct is_greater_than 95
}

@test 'all man_src files pass syntax check' {
    local bad=0
    for f in "$msrc/"_*; do
        zsh -n "$f" 2>/dev/null || (( bad += 1 )) || true
    done
    assert $bad equals 0
}
