#compdef filterbycoverage.sh
# Documentation: https://jgi.doe.gov/data-and-tools/software-tools/bbtools/bb-tools-user-guide/
# FilterByCoverage: filter assembly contigs using pileup coverage stats

local ret=1

_arguments -s -S \
  '(-h --help)'{-h,--help}'[show help]' \
  'in=[file containing input assembly]:file:_files' \
  'cov=[coverage stats generated by pileup]:file:_files' \
  'cov0=[coverage stats before normalization (optional)]:file:_files' \
  'out=[destination of clean output assembly]:file:_files' \
  'outd=[dirty output containing only removed contigs]:file:_files' \
  'minc=[discard contigs with lower average coverage]:n:' \
  'mincov=[discard contigs with lower average coverage]:n:' \
  'minp=[discard contigs with lower percent covered bases]:n:' \
  'minpercent=[discard contigs with lower percent covered]:n:' \
  'minr=[discard contigs with fewer mapped reads]:n:' \
  'minreads=[discard contigs with fewer mapped reads]:n:' \
  'minl=[discard contigs shorter than this after trimming]:n:' \
  'minlength=[discard contigs shorter than this]:n:' \
  'trim=[trim the first and last X bases of each sequence]:n:' \
  'trimends=[trim the first and last X bases of each sequence]:n:' \
  'ratio=[minimum coverage ratio threshold when cov0 set]:value:' \
  'ow=[overwrite files that already exist]:bool:(t f)' \
  'overwrite=[overwrite files that already exist]:bool:(t f)' \
  'app=[append to files that already exist]:bool:(t f)' \
  'append=[append to files that already exist]:bool:(t f)' \
  'zl=[compression level 1 to 9]:level:(1 2 3 4 5 6 7 8 9)' \
  'ziplevel=[compression level 1 to 9]:level:(1 2 3 4 5 6 7 8 9)' \
  '*:file:_files' && ret=0

return ret
