#compdef geocode.py
# Documentation: https://mintpy.readthedocs.io/en/latest/api/cli/
# MintPy resample files between radar and geo coordinates

local ret=1

_arguments -s -S \
  '(-h --help)'{-h,--help}'[show help]' \
  '(-d --dset)'{-d,--dset}'[dataset to geocode (e.g. height, unwrapPhase)]:dset:' \
  '(-l --lookup)'{-l,--lookup}'[lookup table file generated by InSAR processors]:file:_files' \
  '--lat-file[lookup table file for latitude]:file:_files' \
  '--lon-file[lookup table file for longitude]:file:_files' \
  '(--geo2radar --geo2rdr)'{--geo2radar,--geo2rdr}'[resample geocoded files into radar coordinates]' \
  '(-t --template)'{-t,--template}'[template file with geocoding options]:file:_files' \
  '(-b --bbox)'{-b,--bbox}'[bounding box of area of interest (S N W E)]:bbox:' \
  '(--lalo --lalo-step)'{--lalo,--lalo-step}'[output pixel size in degree in lat/lon]:step:' \
  '(-i --interp)'{-i,--interp}'[interpolation/resampling method]:method:' \
  '--fill[fill value for extrapolation]:value:' \
  '(-n --nprocs)'{-n,--nprocs}'[number of processors for calculation]:n:' \
  '--software[software/module used for interpolation]:software:' \
  '--update[skip resampling if output exists and is newer]' \
  '(-o --output)'{-o,--output}'[output filename]:file:_files' \
  '(--outdir --output-dir)'{--outdir,--output-dir}'[output directory]:dir:_files -/' \
  '--maxMemory[maximum memory allocation]:mem:' \
  '*:file:_files' && ret=0

return ret
