#compdef clearList.sh

local arguments

arguments=(
  {-b,--binary}'[list file sizes with binary prefixes]'
  {-B,--bytes}'[list file sizes in bytes, without any prefixes]'
  {-g,--group}'[list each files group]'
  {-h,--header}'[add a header row to each column]'
  {-H,--links}'[list each files number of hard links]'
  {-i,--inode}'[list each files inode number]'
  {-m,--modified}'[use the modified timestamp field]'
  {-S,--blocks}'[show number of file system blocks]'
  {-t,--time}'[which timestamp field to list (modified, accessed, created)]'
  {-u,--accessed}'[use the accessed timestamp field]'
  {-U,--created}'[use the created timestamp field]'
  '--time-style[how to format timestamps (default, iso, long-iso, full-iso)]'
  '--git[list each files Git status, if tracked or ignored]'
  '--help[display this help and exit]'
  {-v,--version}'[output version information and exit]'
  {-m,--magic-file}'[use LIST as a colon-separated list of magic]'
  {-z,--uncompress}'[try to look inside compressed files]'
  {-Z,--uncompress-noreport}'[only print the contents of compressed files]'
  {-b,--brief}'[do not prepend filenames to output lines]'
  {-c,--checking-printout}'[print the parsed form of the magic file, use in]'
  {-e,--exclude}'[exclude TEST from the list of test to be]'
  {-f,--files-from}'[read the filenames to be examined from FILE]'
  {-F,--separator}'[use string as separator instead of `:]'
  {-i,--mime}'[output MIME type strings (--mime-type and]'
  '--mime-encoding[)]'
  '--apple[output the Apple CREATOR/TYPE]'
  '--extension[output a slash-separated list of extensions]'
  '--mime-type[output the MIME type]'
  '--mime-encoding[output the MIME encoding]'
  {-k,--keep-going}'[dont stop at the first match]'
  {-l,--list}'[list magic strength]'
  {-L,--dereference}'[follow symlinks (default if POSIXLY_CORRECT is set)]'
  {-h,--no-dereference}'[dont follow symlinks (default if POSIXLY_CORRECT is not set) (default)]'
  {-n,--no-buffer}'[do not buffer output]'
  {-N,--no-pad}'[do not pad output]'
  {-0,--print0}'[terminate filenames with ASCII NUL]'
  {-p,--preserve-date}'[preserve access times on files]'
  {-P,--parameter}'[set file engine parameter limits]'
  {-r,--raw}'[dont translate unprintable chars to \ooo]'
  {-s,--special-files}'[treat special (block/char devices) files as]'
  {-C,--compile}'[compile file specified by -m]'
  {-d,--debug}'[print debugging messages]'
  {-0,--null}'[end each output line with NUL, not newline]'
  {-a,--all}'[write counts for all files, not just directories]'
  '--apparent-size[print apparent sizes, rather than disk usage; although]'
  {-B,--block-size}'[scale sizes by SIZE before printing them; e.g.]'
  {-b,--bytes}'[equivalent to --apparent-size --block-size=1]'
  {-c,--total}'[produce a grand total]'
  {-D,--dereference-args}'[dereference only symlinks that are listed on the]'
  {-d,--max-depth}'[print the total for a directory (or file, with --all)]'
  '--summarize[]'
  '--files0-from[summarize disk usage of the]'
  '-H[equivalent to --dereference-args (-D)]'
  {-h,--human-readable}'[print sizes in human readable format (e.g., 1K 234M 2G)]'
  '--inodes[list inode usage information instead of block usage]'
  '-k[like --block-size=1K]'
  {-L,--dereference}'[dereference all symbolic links]'
  {-l,--count-links}'[count sizes many times if hard linked]'
  '-m[like --block-size=1M]'
  {-P,--no-dereference}'[dont follow any symbolic links (this is the default)]'
  {-S,--separate-dirs}'[for directories do not include size of subdirectories]'
  '--si[like -h, but use powers of 1000 not 1024]'
  {-s,--summarize}'[display only a total for each argument]'
  {-t,--threshold}'[exclude entries smaller than SIZE if positive]'
  '--time[show time of the last modification of any file in the]'
  '--time[show time as WORD instead of modification time:]'
  '--time-style[show times using STYLE, which can be:]'
  {-X,--exclude-from}'[exclude files that match any pattern in FILE]'
  '--exclude[exclude files that match PATTERN]'
  {-x,--one-file-system}'[skip directories on different file systems]'
  '--help[display this help and exit]'
  '--version[output version information and exit]'
  {-L,--dereference}'[follow links]'
  {-f,--file-system}'[display file system status instead of file status]'
  {-c,--format}'[use the specified FORMAT instead of the default;]'
  '--printf[like --format, but interpret backslash escapes]'
  {-t,--terse}'[print the information in terse form]'
  '--help[display this help and exit]'
  '--version[output version information and exit]'
  '--terse[equivalent to the following FORMAT:]'
  {--terse,--file-system}'[equivalent to the following FORMAT:]'
  '*:filename:_files'
)

_arguments -s $arguments
