#compdef pulledpork.pl

local arguments

arguments=(
  {-O,-s}'[output directory> -D <Distro> -S <SnortVer>]'
  '-p[to your snort binary> -C <path to your snort.conf> -t <sostub output path>]'
  '-h[path> -H <signal_name> -I (security|connectivity|balanced) -i <path to disablesid.conf>]'
  '-b[to dropsid.conf> -e <path to enablesid.conf> -M <path to modifysid.conf>]'
  '-r[to docs folder> -K <directory for separate rules files>]'
  '-help[/? Print this help info.]'
  '-b[the dropsid config file lives.]'
  '-C[to your snort.conf]'
  '-c[the pulledpork config file lives.]'
  '-d[not verify signature of rules tarball, i.e. downloading fron non VRT or ET locations.]'
  '-D[distro are you running on, for the so_rules]'
  '-e[the enablesid config file lives.]'
  '-E[ONLY the enabled rules to the output files.]'
  '-g[(download tarball rule file(s) and do NOT process)]'
  '-h[to the sid_changelog if you want to keep one?]'
  '-H[signal_name to the pids listed in the config file (SIGHUP or SIGUSR2)]'
  '-I[a base ruleset( -I security,connectivity,or balanced, see README.RULESET)]'
  '-i[the disablesid config file lives.]'
  '-k[the rules in separate files (using same file names as found when reading)]'
  '-K[(what directory) do you want me to put the separate rules files?]'
  '-l[important Info to Syslog (Errors, Successful run etc, all items logged as WARN or higher)]'
  '-L[do you want me to read your local.rules for inclusion in sid-msg.map]'
  '-m[do you want me to put the sid-msg.map file?]'
  '-M[the modifysid config file lives.]'
  '-n[everything other than download of new files (disablesid, etc)]'
  '-o[do you want me to put generic rules file?]'
  '-O[the oinkcode on the command line (necessary for some users)]'
  '-p[to your Snort binary]'
  '-P[rules even if no new rules were downloaded]'
  '-R[processing enablesid, return the rules to their ORIGINAL state]'
  '-r[do you want me to put the reference docs (xxxx.txt)]'
  '-S[version of snort are you using (2.8.6 or 2.9.0) are valid values]'
  '-s[do you want me to put the so_rules?]'
  '-T[text based rules files only, i.e. DO NOT process so_rules]'
  '-u[do you want me to pull the rules tarball from]'
  '-V[version and exit]'
  '-v[mode, you know.. for troubleshooting and such nonsense.]'
  '-vv[verbose mode, you know.. for in-depth troubleshooting and other such nonsense.]'
  '-w[the SSL verification (if there are issues pulling down rule files)]'
  '-W[you want to work around the issue where some implementations of LWP do not work with pulledporks proxy configuration.]'
  '*:filename:_files'
)

_arguments -s $arguments
