name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        zsh-version: ['default']
      fail-fast: true

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zsh vim python3 curl git


      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: zsh-more-completions


      - name: Set terminal size variables
        run: |
          echo "TERM=xterm" >> "$GITHUB_ENV"
          echo "COLUMNS=120" >> "$GITHUB_ENV"
          echo "LINES=40" >> "$GITHUB_ENV"

      - name: Set up zunit
        run: |
          mkdir .bin
          curl -L https://raw.githubusercontent.com/molovo/revolver/master/revolver > .bin/revolver
          chmod u+x .bin/revolver
          export PATH="$PWD/.bin:$PATH"
          git clone https://github.com/MenkeTechnologies/zunit
          cd zunit
          ./build.zsh
          echo "$PWD" >> $GITHUB_PATH
          cd ..
          echo "$PWD/.bin" >> $GITHUB_PATH

      - name: Run tests
        run: |
          cd zsh-more-completions
          zunit --verbose tests/*.zsh
